[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wstd = { path = "../../../wstd" }
wstd-axum = { path = "../../" }
axum = { version = "0.8.6", default-features = false }
